# Configuration for LLVM compilation
set(MIEROS ON CACHE BOOL "")
set(target "x86_64-pc-mieros-elf")

# General configuration
set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE PATH "")
set(CMAKE_INSTALL_PREFIX "${CROSS_PATH}/host-llvm" CACHE PATH "")

set(LLVM_TABLEGEN "${CROSS_PATH}/llvm-host-tbl-build/bin/llvm-tblgen" CACHE PATH "")
set(CLANG_TABLEGEN "${CROSS_PATH}/llvm-host-tbl-build/bin/clang-tblgen" CACHE PATH "")

set(DEFAULT_SYSROOT ${SYSROOT_PATH} CACHE PATH "")

set(LLVM_DEFAULT_TARGET_TRIPLE "x86_64-pc-mieros-elf" CACHE STRING "")
set(LLVM_RUNTIME_TARGETS ${LLVM_DEFAULT_TARGET_TRIPLE} CACHE STRING "")
set(LLVM_TARGET_ARCH "x86_64" CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD "X86" CACHE STRING "")

set(LLVM_ENABLE_PROJECTS "clang;lld" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt;libcxx;libcxxabi;libunwind" CACHE STRING "")

set(LLVM_ENABLE_THREADS OFF CACHE BOOL "")
set(LLVM_INSTALL_TOOLCHAIN_ONLY OFF CACHE BOOL "")

set(CMAKE_BUILD_TYPE Release CACHE STRING "")

# Compiler RT configuration
set(RUNTIMES_${target}_CMAKE_C_FLAGS "-nostdlib -nostdlib++" CACHE STRING "")
set(RUNTIMES_${target}_CMAKE_CXX_FLAGS "-nostdlib -nostdlib++" CACHE STRING "")
set(RUNTIMES_${target}_COMPILER_RT_BUILD_BUILTINS ON CACHE BOOL "")
set(RUNTIMES_${target}_COMPILER_RT_BUILD_XRAY OFF CACHE BOOL "")
set(RUNTIMES_${target}_COMPILER_RT_BUILD_MEMPROF OFF CACHE BOOL "")
set(RUNTIMES_${target}_COMPILER_RT_BUILD_SANITIZERS OFF CACHE BOOL "")
set(RUNTIMES_${target}_COMPILER_RT_BUILD_LIBFUZZER OFF CACHE BOOL "")
set(RUNTIMES_${target}_COMPILER_RT_BUILD_ORC OFF CACHE BOOL "")
set(RUNTIMES_${target}_COMPILER_RT_BUILD_PROFILE OFF CACHE BOOL "")
set(RUNTIMES_${target}_COMPILER_RT_INCLUDE_TESTS OFF CACHE BOOL "")

set(BUILTINS_${target}_CMAKE_C_FLAGS "" CACHE STRING "")
set(BUILTINS_${target}_CMAKE_CXX_FLAGS "" CACHE STRING "")
set(BUILTINS_${target}_COMPILER_RT_EXCLUDE_ATOMIC_BUILTIN OFF CACHE BOOL "")

# LibCXX configuration
set(RUNTIMES_${target}_LIBCXX_ENABLE_THREADS OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXX_ENABLE_STATIC ON CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXX_INCLUDE_TESTS OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXX_ENABLE_ABI_LINKER_SCRIPT OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON CACHE BOOL "")

# LibCXXAbi configuration
set(RUNTIMES_${target}_LIBCXXABI_ENABLE_THREADS OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXXABI_ENABLE_STATIC ON CACHE BOOL "")
set(RUNTIMES_${target}_LIBCXXABI_INCLUDE_TESTS OFF CACHE BOOL "")

# LibUnwind configuration
set(RUNTIMES_${target}_LIBUNWIND_ENABLE_THREADS OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
set(RUNTIMES_${target}_LIBUNWIND_ENABLE_STATIC ON CACHE BOOL "")
set(RUNTIMES_${target}_LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")

